before:
  hooks:
    - go mod tidy

builds:
  - binary: intercept
    id: intercept
    main: cmd/intercept/intercept.go
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - 386
      - arm
      - arm64
  - binary: collab
    id: collab
    main: cmd/collab/collab.go
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - 386
      - arm
      - arm64

archives:
  - id: tgz
    format: tar.gz
    replacements:
        darwin: macOS
    format_overrides:
        - goos: windows
          format: zip